function showText() {
	let random_num = Math.floor(Math.random() * 5) + 1;

	if (random_num === 1) {
		document.getElementById("generate_text").innerHTML = 
	"<h3>A Midsummer Night\'s Dream</h3>\
	<p>\"A Midsummer Night's Dream\" is a comedy written by William Shakespeare in the late 16th century. The play is set in Athens and the surrounding forest and tells the story of several groups of characters whose lives become entwined through a series of magical and comical mishaps.<br><br>The play begins with the impending marriage of Theseus, the Duke of Athens, and Hippolyta, the Queen of the Amazons. Meanwhile, a group of amateur actors led by Bottom are preparing to put on a play for the wedding celebration.<br><br>In the forest outside Athens, the fairy king and queen, Oberon and Titania, are engaged in a dispute over a young Indian prince. Oberon enlists the help of his mischievous servant, Puck, to use a love potion to make Titania fall in love with the first person she sees upon waking up. Oberon also uses the potion to make the Athenian nobleman Demetrius fall in love with Helena, who is in love with him but is spurned in favor of Hermia, who is in turn in love with Lysander.<br><br>Puck\'s antics lead to a series of mistaken identities and misadventures in the forest, with the four young lovers wandering in confusion and encountering the group of amateur actors, who have been magically transformed into donkeys.<br><br>In the end, the love potion is undone and the couples are reunited, while Oberon and Titania reconcile and bless the marriage of Theseus and Hippolyta. The amateur actors\' play is performed to the delight of the wedding guests, including the fairies, who provide some magical enhancements.<br><br>Throughout the play, Shakespeare explores themes of love, magic, and the transformative power of art. The play is filled with whimsical and fantastical elements, including mischievous fairies, a love potion, and a group of bumbling actors.<br><br>The play\'s central love triangle between Demetrius, Helena, and Hermia provides a commentary on the irrationality of love and the foolishness of those who try to control it. Meanwhile, the magical elements of the play serve as a reminder of the power of imagination and the importance of the arts in enriching our lives.<br><br>In conclusion, \"A Midsummer Night\'s Dream\" is a delightful and whimsical comedy that showcases Shakespeare\'s skill at blending humor, romance, and fantasy. The play's magical elements and colorful characters continue to enchant audiences to this day, while its exploration of the complexities of love and the transformative power of art remain as relevant as ever.<br></p>";
	
	document.getElementById("generate_text").style.padding = "0 3%";
	document.getElementById("generate_text").style.fontSize = "1rem";
	}

	else if (random_num === 2) {
		document.getElementById("generate_text").innerHTML = 
	"<h3>Hamlet</h3>\
	<p>\"Hamlet\" is a tragedy written by William Shakespeare in the early 17th century. The play is set in Denmark and tells the story of Prince Hamlet, who is called upon to avenge the murder of his father by his uncle, Claudius. The play explores themes of revenge, madness, betrayal, and mortality.<br><br>The play begins with the ghost of Hamlet\'s father appearing to him and revealing that he was murdered by Claudius, who has now taken the throne and married Hamlet\'s mother, Gertrude. Hamlet, who is distraught by the revelation, decides to feign madness and plot his revenge.<br><br>Hamlet\'s behavior becomes increasingly erratic, causing concern among his family and friends. Ophelia, Hamlet\'s love interest, is caught between her love for him and her loyalty to her father, Polonius, who is suspicious of Hamlet\'s motives. Hamlet\'s friends Rosencrantz and Guildenstern are enlisted by Claudius to spy on him and report back on his behavior.<br><br>As Hamlet\'s madness intensifies, he begins to plot his revenge against Claudius. He puts on a play that reenacts his father\'s murder, hoping to incite a reaction from Claudius that will confirm his guilt. When Claudius confesses to the crime, Hamlet prepares to kill him but hesitates when he sees him praying, fearing that he will be sent to heaven rather than to hell.<br><br>Meanwhile, Polonius is killed by Hamlet, who mistakes him for Claudius. Ophelia, driven to madness by her father\'s death and Hamlet\'s erratic behavior, drowns herself. Laertes, Ophelia\'s brother, returns to Denmark seeking revenge against Hamlet for his family\'s deaths. Claudius and Laertes plot to kill Hamlet in a fencing match, but the plan backfires and both Laertes and Claudius are killed, along with Hamlet.<br><br>In the final scene, Horatio, Hamlet\'s loyal friend, reflects on the tragic events and tells Prince Fortinbras of Norway, who has been watching the drama unfold, that he should take the throne of Denmark. Hamlet is remembered as a tragic hero who sought justice for his father\'s murder, but whose obsession with revenge ultimately led to his downfall.<br><br>In conclusion, \"Hamlet\" is a complex and powerful tragedy that explores the depths of human emotion and the consequences of seeking revenge. Shakespeare delves into themes of madness, betrayal, and mortality, showcasing the destructive power of unchecked ambition and the toll it takes on those who pursue it. The play has become a timeless classic, with its complex characters and themes continuing to resonate with audiences to this day.</p>";
	
	document.getElementById("generate_text").style.padding = "0 3%";
	document.getElementById("generate_text").style.fontSize = "1rem";
	}

	else if (random_num === 3) {
		document.getElementById("generate_text").innerHTML = 
	"<h3>Macbeth</h3>\
	<p>\"Macbeth\" is a tragedy written by William Shakespeare in the early 17th century. The play is set in Scotland and tells the story of Macbeth, a Scottish general who receives a prophecy from three witches that he will become king. Driven by ambition and aided by his wife, Lady Macbeth, Macbeth sets out on a path of ruthless murder and deception to seize the throne.<br><br>The play opens with Macbeth and his friend Banquo encountering the three witches, who predict that Macbeth will become king and that Banquo's descendants will also inherit the throne. Macbeth becomes obsessed with the idea of becoming king and, at the urging of his wife, Lady Macbeth, he murders King Duncan in his sleep. He then frames Duncan's servants for the crime and takes the throne for himself.<br><br>As Macbeth becomes increasingly paranoid and unstable, he commits further murders to maintain his power. Lady Macbeth, who initially encouraged her husband\'s actions, begins to suffer from guilt and madness, eventually taking her own life.<br><br>Meanwhile, Macbeth\'s former ally, Macduff, leads a rebellion against him, seeking to restore the rightful heir to the throne. In a final battle, Macbeth is defeated and killed by Macduff, who is revealed to be the only person not born of a woman, fulfilling another prophecy from the witches.<br><br>Throughout the play, Shakespeare explores themes of ambition, guilt, and the corrupting influence of power. Macbeth\'s descent into madness and paranoia is a warning against the dangers of unchecked ambition, while Lady Macbeth\'s guilt and eventual breakdown illustrate the toll that such actions can take on one\'s psyche.<br><br>The play also features a number of memorable characters, including the witches, who serve as an ominous and supernatural presence throughout the story, and the tragic figure of Lady Macbeth, whose ambition and guilt ultimately lead to her downfall.<br><br>In conclusion, \"Macbeth\" is a dark and powerful tragedy that explores the consequences of unchecked ambition and the corrupting influence of power. Shakespeare\'s masterful storytelling and memorable characters have made the play a timeless classic, with its themes continuing to resonate with audiences today. The play serves as a cautionary tale about the dangers of ambition and the importance of recognizing the consequences of our actions.</p>";
	
	document.getElementById("generate_text").style.padding = "0 3%";
	document.getElementById("generate_text").style.fontSize = "1rem";
	}
	
	else if (random_num === 4) {
		document.getElementById("generate_text").innerHTML = 
	"<h3>Romeo and Juliet</h3>\
	<p>\"Romeo and Juliet\" is a tragedy written by William Shakespeare in the late 16th century. The play is set in the city of Verona, Italy and tells the story of two young lovers, Romeo Montague and Juliet Capulet, who belong to feuding families. The play explores themes of love, hate, fate, and the destructive power of rivalry.<br><br>The play begins with a prologue, which introduces the audience to the conflict between the two families and the doomed fate of the young lovers. The first scene takes place in the streets of Verona, where a brawl breaks out between the Montagues and the Capulets. Prince Escalus, the ruler of Verona, intervenes and threatens the two families with death if they continue their feud.<br><br>Meanwhile, Romeo, who is a Montague, is love-struck with a girl named Rosaline, who does not reciprocate his feelings. Romeo\'s friend Benvolio suggests that they attend the Capulet\'s masquerade ball in hopes of finding another girl for Romeo. Romeo agrees to attend the ball, hoping to forget about Rosaline.<br><br>At the ball, Romeo sees Juliet for the first time and falls instantly in love with her. Juliet is also smitten with Romeo, and they share a passionate dance. However, they soon discover that they belong to rival families, and their love is forbidden. Despite this, they continue to meet in secret with the help of Friar Laurence, who marries them in the hopes that their union will end the feud between the families.<br><br>The feud, however, intensifies when Tybalt, Juliet\'s hot-headed cousin, challenges Romeo to a duel. Romeo tries to avoid the conflict but is eventually forced to fight when Tybalt kills Romeo\'s friend Mercutio. In a fit of rage, Romeo kills Tybalt and is banished from Verona by the prince.<br><br>As Romeo is leaving, he spends one last night with Juliet. The next day, Juliet\'s father, unaware of her marriage to Romeo, arranges for her to marry Paris, a wealthy nobleman. Juliet refuses, and in desperation, seeks the help of Friar Laurence, who gives her a potion that will make her appear dead for 42 hours. The plan is for Romeo to rescue her from the Capulet tomb and flee with her to Mantua.<br><br>However, Romeo does not receive the message about the plan, and believing Juliet to be truly dead, he buys poison and takes his own life next to her body. Juliet awakens from the potion to find Romeo dead beside her and takes her own life with his dagger. The two families, upon discovering the tragedy, finally end their feud and vow to reconcile.<br><br>In conclusion, \"Romeo and Juliet\" is a tragic story of young love that is destroyed by the senseless feud between two families. Shakespeare explores the power of love and the consequences of hate, showcasing the destructive nature of violence and the inevitability of fate. The play has remained a timeless classic for centuries, with its themes and characters continuing to resonate with audiences to this day.</p>";
		
	document.getElementById("generate_text").style.padding = "0 3%";
	document.getElementById("generate_text").style.fontSize = "1rem";
	}

	else if (random_num === 5) {
		document.getElementById("generate_text").innerHTML = 
	"<h3>The Tempest</h3>\
	<p>\"The Tempest\" is a play by William Shakespeare, believed to have been written in the early 17th century. The play is set on a remote island and tells the story of Prospero, the rightful Duke of Milan, who has been usurped by his own brother and left to die at sea with his young daughter, Miranda. Prospero has spent twelve years on the island, developing his magical abilities and planning his revenge.<br><br>The play begins with a storm created by Prospero, which causes a ship carrying his brother and other nobles to crash on the island. Prospero uses his magic to separate the shipwrecked passengers into different groups and begins to manipulate events to achieve his ultimate goal of regaining his position as Duke of Milan.<br><br>Prospero\'s plan involves using his magic to create illusions and manipulate the people on the island, including his own daughter and the shipwrecked nobles. He orchestrates a romance between his daughter and Ferdinand, the son of the King of Naples, in order to secure an alliance with Naples that will help him regain his power. He also confronts his brother Antonio and forces him to repent for his past deeds.<br><br>Throughout the play, Shakespeare explores themes of power, justice, and forgiveness. Prospero\'s actions are driven by his desire for revenge, but he ultimately comes to realize that forgiveness and reconciliation are more important than his own desire for power.<br><br>The play also features a number of memorable characters, including Caliban, a native of the island who is enslaved by Prospero and rebels against him, and Ariel, a spirit who serves Prospero and helps him with his magical machinations.<br><br>In the end, Prospero forgives his enemies and relinquishes his magic, choosing to return to Milan and live a life of simplicity and peace. The play ends with Prospero delivering a powerful speech about the transient nature of life and the importance of forgiveness.<br><br>In conclusion, \"The Tempest\" is a complex and thought-provoking play that explores themes of power, revenge, and forgiveness. The play's magical elements and memorable characters, combined with Shakespeare's masterful storytelling, have made it a classic of English literature. The play's message about the importance of forgiveness and the fleeting nature of power continues to resonate with audiences today.</p>";
	
	document.getElementById("generate_text").style.padding = "0 3%";
	document.getElementById("generate_text").style.fontSize = "1rem";
	}

};


function clearText() {
	document.getElementById("generate_text").innerHTML = "<em>Your text will appear here!</em>";
	document.getElementById("generate_text").style.padding = "15% 0";
	document.getElementById("generate_text").style.fontSize = "1.5rem";
}


function change_font() {
	let val = document.getElementById("ft_js").value;
	document.getElementById("generate_text").style.fontFamily = val;
}